Feature/turbaniak/2 list of jobs
tomazi776/JobProcessor.App pull request #5
Opened 2021-02-15 21:09 UTC by tomazi776

2021-02-25 08:22 UTC, MichalZawadzki commented on JobProcessor.App/App_Start/RouteConfig.cs
> +                defaults: new { controller = "Jobs", action = "Index", startIndex = 0, pageSize = 10 });
I like it

2021-02-25 09:31 UTC, MichalZawadzki requested changes
Better than the last time ;)

2021-02-25 09:31 UTC, MichalZawadzki commented on JobProcessor.App/Controllers/JobsController.cs
> +            return View(new JobCreationVM()
Why do you always create a new object?
In my opinion, you should redirect to the GET View in case of success and pass the wrong object with a ModelState in case of failure

2021-02-25 09:31 UTC, MichalZawadzki commented on JobProcessor.App/App_Start/RouteConfig.cs
> +                defaults: new { controller = "Jobs", action = "Index", startIndex = 0, pageSize = 10 });
But better is pageNumber, not startIndex 
pageNumber is more intuitive for the user

2021-02-25 09:31 UTC, MichalZawadzki commented on JobProcessor.App/Views/Jobs/Index.cshtml
> +                       new { startIndex = currentPageStartIndex, pageSize = currentPageSize },
The next button shouldn't be shown when all items fit into one page
I had 19 elements and pageSize was 20 and I could see and use a next button

2021-02-25 09:31 UTC, MichalZawadzki commented on JobProcessor.DataAccess/Services/Metadata.cs
> +            PageSize = 2;
Extract this DefaultPageSize to web.config

2021-02-25 09:31 UTC, MichalZawadzki commented on JobProcessor.Domain/Services/IntermediaryMapper.cs
> +        public IEnumerable<Models.Job> MapManyDALToDomainModel(IEnumerable<DataAccess.Entities.Job> jobs)
Use usings to skip DataAccess.Entities.Job and use just Job

2021-02-25 09:31 UTC, MichalZawadzki commented on JobProcessor.Domain/Services/JobService.cs
> +            if (withMetadata is null)
You can simplify it, checking if withMetadata is null is inside the repo method

2021-03-09 22:51 UTC, tomazi776 commented on JobProcessor.App/Controllers/JobsController.cs
> +            return View(new JobCreationVM()
Should be fine now

2021-03-09 22:52 UTC, tomazi776 commented
Adhered to suggestions, should be ok now.

2021-03-20 12:30 UTC, merged